# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1529, 1012)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMenu.setGeometry(QtCore.QRect(60, 10, 1371, 941))
        self.tabMenu.setObjectName("tabMenu")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.lineEdit = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab1)
        self.pushButton.setGeometry(QtCore.QRect(260, 22, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.tab1)
        self.textEdit.setGeometry(QtCore.QRect(20, 70, 311, 491))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 580, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_3.setGeometry(QtCore.QRect(244, 580, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabMenu.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 30, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabMenu.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1529, 21))
        self.menubar.setObjectName("menubar")
        self.menufILE = QtWidgets.QMenu(self.menubar)
        self.menufILE.setObjectName("menufILE")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menufILE.addAction(self.actionOpen)
        self.menufILE.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menufILE.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "Select a file"))
        self.pushButton.setText(_translate("MainWindow", "Browse..."))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Load a file, then edit it if needed</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Create a new file"))
        self.pushButton_3.setText(_translate("MainWindow", "Capture Inputs"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.lineEdit_2.setText(_translate("MainWindow", "Select a file"))
        self.pushButton_4.setText(_translate("MainWindow", "Browse..."))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.menufILE.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
